const KEY='verde-state-v1';
const seedPlants=()=>JSON.parse(localStorage.getItem(KEY)||'null')||{plants:[],rooms:['Гостиная','Спальня','Кухня','Балкон'],history:[],notes:{},settings:{notify:true,theme:'light'}};
let state=seedPlants(); let view='today'; let selected=null;
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const dateKey=d=>{const x=new Date(d);return new Date(x.getFullYear(),x.getMonth(),x.getDate()).toISOString().slice(0,10)};
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const fmt=d=>new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long'}).format(new Date(d));
const fmtShort=d=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit'}).format(new Date(d));
const today=dateKey(new Date());
function due(p){return p.nextWatering<=today}
function daysUntil(date){return Math.ceil((new Date(date)-new Date(today))/86400000)}
function greeting(){const h=new Date().getHours();return h<6?'Доброй ночи':h<12?'Доброе утро':h<18?'Добрый день':'Добрый вечер'}
function nav(){return `<nav class="nav">${[['today','⌂','Сегодня'],['plants','♧','Растения'],['calendar','□','Календарь'],['more','⋯','Ещё']].map(x=>`<button data-view="${x[0]}" class="${view===x[0]?'active':''}"><span class="nav-icon">${x[1]}</span>${x[2]}</button>`).join('')}</nav>`}
function header(){return `<div class="top"><div class="brand">verde</div><div class="sub">уход за домом</div></div>`}
function render(){const app=$('#app');let content=view==='today'?todayPage():view==='plants'?plantsPage():view==='calendar'?calendarPage():morePage();app.innerHTML=header()+content+nav()+'<button class="fab" id="fab">+</button>';document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('#fab').onclick=()=>openAdd();}
function todayPage(){const duePlants=state.plants.filter(due), upcoming=state.plants.filter(p=>p.nextWatering>today).sort((a,b)=>a.nextWatering.localeCompare(b.nextWatering)).slice(0,5);return `<main class="page"><div class="date">${new Intl.DateTimeFormat('ru-RU',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</div><div class="greeting">${greeting()}.</div><div class="stats"><div class="stat"><b>${duePlants.length}</b><span>Сегодня</span></div><div class="stat"><b>${state.plants.filter(p=>p.nextWatering<today).length}</b><span>Просрочено</span></div><div class="stat"><b>${upcoming.length}</b><span>Ближайшие</span></div><div class="stat"><b>${state.plants.length}</b><span>Растений</span></div></div><div class="section-title">Сегодня</div>${duePlants.length?duePlants.map(taskCard).join(''):`<div class="card empty">Сегодня всё спокойно.<br>Можно просто посмотреть на растения.</div>`}<div class="section-title">Дальше</div>${upcoming.length?upcoming.map(p=>`<div class="card task"><div class="row"><div><div class="plant-title">${esc(p.name)}</div><div class="meta">${esc(p.room||'Без комнаты')} · ${daysUntil(p.nextWatering)===1?'завтра':'через '+daysUntil(p.nextWatering)+' дн.'}</div></div><span class="pill">${fmt(p.nextWatering)}</span></div></div>`).join(''):`<div class="card empty">Добавьте растения, чтобы видеть будущий уход.</div>`}<div class="section-title">Состояние дома</div><div class="card action-card"><div class="row"><div><div class="plant-title">${state.plants.length} растений</div><div class="meta">${Math.max(0,state.plants.length-duePlants.length)} всё хорошо · ${duePlants.length} требуют внимания</div></div><span class="pill">Verde</span></div></div></main>`}
function taskCard(p){return `<div class="card task"><div class="row"><div onclick="openPlant('${p.id}')"><div class="plant-title">${esc(p.name)}</div><div class="meta">${esc(p.room||'Без комнаты')}</div></div><button class="primary" onclick="water('${p.id}')">ПОЛИТЬ</button></div><div class="meta" style="margin-top:12px">${esc(p.tip)}</div></div>`}
function plantsPage(){return `<main class="page"><div class="greeting" style="margin-bottom:8px">Мои растения</div><div class="date">${state.plants.length} растений</div><div style="margin-top:18px"><input class="search" id="plantSearch" placeholder="Найти растение"></div><div class="chips"><button class="chip active">Все</button>${state.rooms.map(r=>`<button class="chip">${esc(r)}</button>`).join('')}</div><div class="grid" id="plantGrid">${plantCards(state.plants)}</div></main>`}
function plantCards(arr){if(!arr.length)return `<div class="empty" style="grid-column:1/-1">Пока нет растений.<br>Нажмите «+», чтобы добавить первое.</div>`;return arr.map(p=>`<article class="card plant-card" onclick="openPlant('${p.id}')"><div class="photo">⌁</div><div class="plant-body"><div class="plant-title">${esc(p.name)}</div><div class="meta">${esc(p.room||'Без комнаты')}</div><div class="next">${due(p)?'Полив сегодня':`Полив ${fmt(p.nextWatering)}`}</div></div></article>`).join('')}
function calendarPage(){const now=new Date();const y=now.getFullYear(),m=now.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=(first.getDay()+6)%7;let cells=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<div class="cal-cell head">${x}</div>`).join('');for(let i=0;i<start;i++)cells+='<div></div>';for(let d=1;d<=days;d++){const k=dateKey(new Date(y,m,d));const has=state.plants.some(p=>p.nextWatering===k)||state.history.some(h=>h.date===k);cells+=`<div class="cal-cell ${k===today?'today':''}">${d}${has?'<div class="dot"></div>':''}</div>`}const month=new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(now);return `<main class="page"><div class="greeting" style="margin-bottom:18px">Календарь</div><div class="calendar"><div class="cal-head"><button class="ghost">‹</button><b>${month}</b><button class="ghost">›</button></div><div class="cal-grid">${cells}</div></div><div class="section-title">Последний уход</div><div class="card action-card">${state.history.length?state.history.slice(-8).reverse().map(h=>`<div class="history-row"><span>${esc(h.name)}</span><span class="muted">${esc(h.type)} · ${fmtShort(h.date)}</span></div>`).join(''):'<div class="muted">История появится после первого полива.</div>'}</div></main>`}
function morePage(){return `<main class="page"><div class="greeting">Ещё</div><div class="list"><div class="setting" onclick="openCatalog()"><span>База растений</span><b>›</b></div><div class="setting" onclick="openRooms()"><span>Комнаты</span><b>›</b></div><div class="setting"><span>Напоминания</span><label><input type="checkbox" ${state.settings.notify?'checked':''} onchange="toggleNotify(this.checked)"></label></div><div class="setting"><span>Тема</span><select onchange="setTheme(this.value)"><option value="light">Светлая</option><option value="dark">Тёмная</option></select></div><div class="setting onclick" onclick="exportData()"><span>Экспорт данных</span><b>↓</b></div><div class="setting" onclick="importData()"><span>Импорт данных</span><b>↑</b></div><div class="card action-card"><b>Verde</b><div class="meta">Локальный уход за домашними растениями · v1.0</div></div></div></main>`}
function openPlant(id){selected=state.plants.find(p=>p.id===id);if(!selected)return;const history=state.history.filter(h=>h.plantId===id).slice(-10).reverse();$('#app').innerHTML=header()+`<main class="page"><button class="back" onclick="render()">← Назад</button><div class="detail-photo">⌁</div><div class="hero"><h1>${esc(selected.name)}</h1><div class="latin">${esc(selected.latin)}</div><div class="meta">${esc(selected.room||'Без комнаты')}</div></div><div class="card action-card"><div class="section-title" style="margin-top:0">Следующий уход</div><div class="big-status">${due(selected)?'Сегодня':fmt(selected.nextWatering)}</div><div class="meta">Обычно каждые ${selected.interval} дней</div><button class="primary" style="margin-top:16px;width:100%" onclick="water('${selected.id}')">ПОЛИТЬ</button></div><div class="info-grid"><div class="info"><small>Свет</small><b>${esc(selected.light)}</b></div><div class="info"><small>Полив</small><b>${selected.interval} дней</b></div></div><div class="section-title">Совет</div><div class="card action-card">${esc(selected.tip)}</div><div class="section-title">История</div><div class="card action-card">${history.length?history.map(h=>`<div class="history-row"><span>${esc(h.type)}</span><span class="muted">${fmtShort(h.date)}${h.amount?' · '+esc(h.amount)+' мл':''}</span></div>`).join(''):'<div class="muted">Пока нет записей.</div>'}</div><div class="section-title">Заметка</div><div class="card action-card"><textarea id="note" rows="4" placeholder="Например: появился новый лист">${esc(state.notes[id]||'')}</textarea><button class="ghost" style="margin-top:10px;width:100%" onclick="saveNote('${id}')">Сохранить заметку</button></div><button class="ghost" style="width:100%;margin-top:10px" onclick="deletePlant('${id}')">Удалить растение</button></main>`+nav()}
function water(id){const p=state.plants.find(x=>x.id===id);if(!p)return;const amount=prompt('Объём воды, мл (можно оставить пустым):','');p.lastWatering=today;p.nextWatering=dateKey(addDays(new Date(),p.interval));state.history.push({id:Date.now(),plantId:id,name:p.name,type:'Полив',date:today,amount:amount||''});save();toast('Полив записан');selected=null;render()}
function saveNote(id){state.notes[id]=$('#note').value.trim();save();toast('Заметка сохранена')}
function deletePlant(id){if(confirm('Удалить это растение?')){state.plants=state.plants.filter(p=>p.id!==id);save();render()}}
function openAdd(){modal(`<h2>Добавить растение</h2><div class="form"><label>Найти в базе</label><input id="addSearch" placeholder="Например, юкка"><div id="catalogResults" class="list"></div><label>Или создать своё</label><input id="customName" placeholder="Название растения"><select id="room">${state.rooms.map(r=>`<option>${esc(r)}</option>`).join('')}<option value="__new">＋ Новая комната</option></select><div class="actions"><button class="ghost" onclick="closeModal()">Отмена</button><button class="primary" onclick="addCustom()">Добавить своё</button></div></div>`);$('#addSearch').oninput=e=>showCatalogResults(e.target.value);showCatalogResults('')}
function showCatalogResults(q){const r=PLANTS.filter(p=>(p.name+' '+p.latin).toLowerCase().includes(q.toLowerCase())).slice(0,8);$('#catalogResults').innerHTML=r.map(p=>`<button class="setting" onclick="addFromBase('${p.id}')"><span><b>${esc(p.name)}</b><small class="muted" style="display:block">${esc(p.latin)}</small></span><b>＋</b></button>`).join('')}
function addFromBase(id){const b=PLANTS.find(x=>x.id===id);const room=$('#room').value==='__new'?prompt('Название комнаты:','Гостиная'):$('#room').value;if(!room)return;const p={...b,id:'u'+Date.now(),room,lastWatering:today,nextWatering:dateKey(addDays(new Date(),b.interval))};state.plants.push(p);if(!state.rooms.includes(room))state.rooms.push(room);save();closeModal();toast('Растение добавлено');render()}
function addCustom(){let name=$('#customName').value.trim();if(!name)return toast('Введите название');let room=$('#room').value;if(room==='__new'){room=prompt('Название комнаты:','Гостиная')||'Без комнаты';if(!state.rooms.includes(room))state.rooms.push(room)}const p={id:'u'+Date.now(),name,latin:'',interval:7,light:'Не указано',tip:'Наблюдайте за влажностью грунта и корректируйте интервал под условия дома.',room,lastWatering:today,nextWatering:dateKey(addDays(new Date(),7))};state.plants.push(p);save();closeModal();toast('Растение добавлено');render()}
function openCatalog(){modal(`<h2>База Verde</h2><div class="meta">${PLANTS.length} растений</div><input class="search" id="catSearch" style="margin:15px 0" placeholder="Найти растение"><div id="catList" class="list"></div>`);const draw=q=>{$('#catList').innerHTML=PLANTS.filter(p=>(p.name+' '+p.latin).toLowerCase().includes(q.toLowerCase())).map(p=>`<div class="setting"><span><b>${esc(p.name)}</b><small class="muted" style="display:block">${esc(p.latin)} · ${p.interval} дн.</small></span><span class="muted">${esc(p.light)}</span></div>`).join('')};$('#catSearch').oninput=e=>draw(e.target.value);draw('')}
function openRooms(){modal(`<h2>Комнаты</h2><div class="list">${state.rooms.map((r,i)=>`<div class="setting"><span>${esc(r)}</span><b>${state.plants.filter(p=>p.room===r).length}</b></div>`).join('')}</div><button class="primary" style="width:100%;margin-top:14px" onclick="addRoom()">＋ Добавить комнату</button>`)}
function addRoom(){const r=prompt('Название комнаты:');if(r&&!state.rooms.includes(r)){state.rooms.push(r);save();closeModal();openRooms()}}
function modal(html){const m=document.createElement('div');m.className='modal';m.id='modal';m.innerHTML=`<div class="sheet">${html}</div>`;document.body.appendChild(m)}function closeModal(){$('#modal')?.remove()}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function toggleNotify(v){state.settings.notify=v;save();if(v&&'Notification'in window&&Notification.permission==='default')Notification.requestPermission()}
function setTheme(v){state.settings.theme=v;save();document.documentElement.dataset.theme=v}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='verde-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(){const i=document.createElement('input');i.type='file';i.accept='application/json';i.onchange=()=>{const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();render();toast('Данные импортированы')}catch{toast('Не удалось прочитать файл')}};r.readAsText(f)};i.click()}
window.openPlant=openPlant;window.water=water;window.openAdd=openAdd;window.addFromBase=addFromBase;window.addCustom=addCustom;window.closeModal=closeModal;window.saveNote=saveNote;window.deletePlant=deletePlant;window.openCatalog=openCatalog;window.openRooms=openRooms;window.addRoom=addRoom;window.toggleNotify=toggleNotify;window.setTheme=setTheme;window.exportData=exportData;window.importData=importData;
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});render();
